classDiagram
  %% Schemas related to tag: Domestic Payments
  class ActiveOrHistoricCurrencyCode
  class BuildingName
  class BuildingNumber
  class CareOf
  class CountryCode
  class CountrySubDivision
  class Department
  class DistrictName
  class ExternalCategoryPurpose1Code
  class ExternalCreditorReferenceType1Code
  class ExternalDocumentType1Code
  class ExternalProxyAccountType1Code
  class ExternalPurpose1Code
  class Floor
  class ISODateTime
  class Identification_0
  class Identification_1
  class Identification_3
  class Identification_4
  class LEI
  class Name
  class OBActiveCurrencyAndAmount_SimpleType
  class OBActiveOrHistoricCurrencyAndAmount
  class OBAddressType2Code
  class OBInternalAccountIdentification4Code
  class OBInternalExtendedAccountType1Code
  class OBInternalFinancialInstitutionIdentification4Code
  class OBInternalLocalInstrument1Code
  class OBPostalAddress7
  class OBProxy1
  class OBReferredDocumentInformation
  class OBRegulatoryAuthority2
  class OBRegulatoryReporting1
  class OBRemittanceInformation2
  class OBRemittanceInformationStructured
  class OBRisk1
  class OBSCASupportData1
  class OBStructuredRegulatoryReporting3
  class OBSupplementaryData1
  class OBUltimateCreditor1
  class OBUltimateDebtor1
  class OBWriteDomestic2
  class OBWriteDomesticConsent4
  class PostBox
  class PostCode
  class Room
  class SecondaryIdentification
  class StreetName
  class SubDepartment
  class TownName
  class UnitNumber
  OBActiveOrHistoricCurrencyAndAmount --> ActiveOrHistoricCurrencyCode
  OBActiveOrHistoricCurrencyAndAmount --> OBActiveCurrencyAndAmount_SimpleType
  OBPostalAddress7 --> BuildingName
  OBPostalAddress7 --> BuildingNumber
  OBPostalAddress7 --> CareOf
  OBPostalAddress7 --> CountryCode
  OBPostalAddress7 --> CountrySubDivision
  OBPostalAddress7 --> Department
  OBPostalAddress7 --> DistrictName
  OBPostalAddress7 --> Floor
  OBPostalAddress7 --> OBAddressType2Code
  OBPostalAddress7 --> PostBox
  OBPostalAddress7 --> PostCode
  OBPostalAddress7 --> Room
  OBPostalAddress7 --> StreetName
  OBPostalAddress7 --> SubDepartment
  OBPostalAddress7 --> TownName
  OBPostalAddress7 --> UnitNumber
  OBProxy1 --> ExternalProxyAccountType1Code
  OBReferredDocumentInformation --> ExternalDocumentType1Code
  OBRegulatoryAuthority2 --> CountryCode
  OBRegulatoryReporting1 --> OBRegulatoryAuthority2
  OBRegulatoryReporting1 --> OBStructuredRegulatoryReporting3
  OBRemittanceInformation2 --> OBRemittanceInformationStructured
  OBRemittanceInformationStructured --> ExternalCreditorReferenceType1Code
  OBRemittanceInformationStructured --> Identification_3
  OBRemittanceInformationStructured --> Identification_4
  OBRemittanceInformationStructured --> OBReferredDocumentInformation
  OBRisk1 --> ExternalCategoryPurpose1Code
  OBRisk1 --> ExternalPurpose1Code
  OBRisk1 --> OBInternalExtendedAccountType1Code
  OBRisk1 --> OBPostalAddress7
  OBStructuredRegulatoryReporting3 --> CountryCode
  OBStructuredRegulatoryReporting3 --> ISODateTime
  OBStructuredRegulatoryReporting3 --> OBActiveOrHistoricCurrencyAndAmount
  OBUltimateCreditor1 --> LEI
  OBUltimateCreditor1 --> OBInternalAccountIdentification4Code
  OBUltimateCreditor1 --> OBPostalAddress7
  OBUltimateDebtor1 --> LEI
  OBUltimateDebtor1 --> OBInternalAccountIdentification4Code
  OBUltimateDebtor1 --> OBPostalAddress7
  OBWriteDomestic2 --> ActiveOrHistoricCurrencyCode
  OBWriteDomestic2 --> Identification_0
  OBWriteDomestic2 --> Identification_1
  OBWriteDomestic2 --> LEI
  OBWriteDomestic2 --> Name
  OBWriteDomestic2 --> OBActiveCurrencyAndAmount_SimpleType
  OBWriteDomestic2 --> OBInternalAccountIdentification4Code
  OBWriteDomestic2 --> OBInternalFinancialInstitutionIdentification4Code
  OBWriteDomestic2 --> OBInternalLocalInstrument1Code
  OBWriteDomestic2 --> OBPostalAddress7
  OBWriteDomestic2 --> OBProxy1
  OBWriteDomestic2 --> OBRegulatoryReporting1
  OBWriteDomestic2 --> OBRemittanceInformation2
  OBWriteDomestic2 --> OBRisk1
  OBWriteDomestic2 --> OBSupplementaryData1
  OBWriteDomestic2 --> OBUltimateCreditor1
  OBWriteDomestic2 --> OBUltimateDebtor1
  OBWriteDomestic2 --> SecondaryIdentification
  OBWriteDomesticConsent4 --> ActiveOrHistoricCurrencyCode
  OBWriteDomesticConsent4 --> Identification_0
  OBWriteDomesticConsent4 --> Identification_1
  OBWriteDomesticConsent4 --> LEI
  OBWriteDomesticConsent4 --> Name
  OBWriteDomesticConsent4 --> OBActiveCurrencyAndAmount_SimpleType
  OBWriteDomesticConsent4 --> OBInternalAccountIdentification4Code
  OBWriteDomesticConsent4 --> OBInternalFinancialInstitutionIdentification4Code
  OBWriteDomesticConsent4 --> OBInternalLocalInstrument1Code
  OBWriteDomesticConsent4 --> OBPostalAddress7
  OBWriteDomesticConsent4 --> OBProxy1
  OBWriteDomesticConsent4 --> OBRegulatoryReporting1
  OBWriteDomesticConsent4 --> OBRemittanceInformation2
  OBWriteDomesticConsent4 --> OBRisk1
  OBWriteDomesticConsent4 --> OBSCASupportData1
  OBWriteDomesticConsent4 --> OBSupplementaryData1
  OBWriteDomesticConsent4 --> OBUltimateCreditor1
  OBWriteDomesticConsent4 --> OBUltimateDebtor1
  OBWriteDomesticConsent4 --> SecondaryIdentification
