classDiagram
  %% Schemas related to tag: Domestic Standing Orders
  class ActiveOrHistoricCurrencyCode
  class BuildingName
  class BuildingNumber
  class CareOf
  class CountryCode
  class CountrySubDivision
  class Department
  class DistrictName
  class ExternalCategoryPurpose1Code
  class ExternalCreditorReferenceType1Code
  class ExternalDocumentType1Code
  class ExternalProxyAccountType1Code
  class ExternalPurpose1Code
  class Floor
  class Frequency_1
  class ISODateTime
  class Identification_0
  class Identification_1
  class Identification_3
  class Identification_4
  class LEI
  class NumberOfPayments
  class OBActiveCurrencyAndAmount_SimpleType
  class OBActiveOrHistoricCurrencyAndAmount
  class OBAddressType2Code
  class OBExternalMandateClassification1Code
  class OBFrequency6
  class OBFrequency6Code
  class OBInternalAccountIdentification4Code
  class OBInternalExtendedAccountType1Code
  class OBMandateRelatedInformation1
  class OBPostalAddress7
  class OBProxy1
  class OBReferredDocumentInformation
  class OBRegulatoryAuthority2
  class OBRegulatoryReporting1
  class OBRemittanceInformation2
  class OBRemittanceInformationStructured
  class OBRisk1
  class OBSCASupportData1
  class OBStructuredRegulatoryReporting3
  class OBSupplementaryData1
  class OBUltimateCreditor1
  class OBUltimateDebtor1
  class OBWriteDomesticStandingOrder3
  class OBWriteDomesticStandingOrderConsent5
  class PointInTime
  class PostBox
  class PostCode
  class Room
  class SecondaryIdentification
  class StreetName
  class SubDepartment
  class TownName
  class UnitNumber
  OBActiveOrHistoricCurrencyAndAmount --> ActiveOrHistoricCurrencyCode
  OBActiveOrHistoricCurrencyAndAmount --> OBActiveCurrencyAndAmount_SimpleType
  OBFrequency6 --> Frequency_1
  OBFrequency6 --> OBFrequency6Code
  OBFrequency6 --> PointInTime
  OBMandateRelatedInformation1 --> ExternalCategoryPurpose1Code
  OBMandateRelatedInformation1 --> Identification_1
  OBMandateRelatedInformation1 --> OBExternalMandateClassification1Code
  OBMandateRelatedInformation1 --> OBFrequency6
  OBPostalAddress7 --> BuildingName
  OBPostalAddress7 --> BuildingNumber
  OBPostalAddress7 --> CareOf
  OBPostalAddress7 --> CountryCode
  OBPostalAddress7 --> CountrySubDivision
  OBPostalAddress7 --> Department
  OBPostalAddress7 --> DistrictName
  OBPostalAddress7 --> Floor
  OBPostalAddress7 --> OBAddressType2Code
  OBPostalAddress7 --> PostBox
  OBPostalAddress7 --> PostCode
  OBPostalAddress7 --> Room
  OBPostalAddress7 --> StreetName
  OBPostalAddress7 --> SubDepartment
  OBPostalAddress7 --> TownName
  OBPostalAddress7 --> UnitNumber
  OBProxy1 --> ExternalProxyAccountType1Code
  OBReferredDocumentInformation --> ExternalDocumentType1Code
  OBRegulatoryAuthority2 --> CountryCode
  OBRegulatoryReporting1 --> OBRegulatoryAuthority2
  OBRegulatoryReporting1 --> OBStructuredRegulatoryReporting3
  OBRemittanceInformation2 --> OBRemittanceInformationStructured
  OBRemittanceInformationStructured --> ExternalCreditorReferenceType1Code
  OBRemittanceInformationStructured --> Identification_3
  OBRemittanceInformationStructured --> Identification_4
  OBRemittanceInformationStructured --> OBReferredDocumentInformation
  OBRisk1 --> ExternalCategoryPurpose1Code
  OBRisk1 --> ExternalPurpose1Code
  OBRisk1 --> OBInternalExtendedAccountType1Code
  OBRisk1 --> OBPostalAddress7
  OBStructuredRegulatoryReporting3 --> CountryCode
  OBStructuredRegulatoryReporting3 --> ISODateTime
  OBStructuredRegulatoryReporting3 --> OBActiveOrHistoricCurrencyAndAmount
  OBUltimateCreditor1 --> LEI
  OBUltimateCreditor1 --> OBInternalAccountIdentification4Code
  OBUltimateCreditor1 --> OBPostalAddress7
  OBUltimateDebtor1 --> LEI
  OBUltimateDebtor1 --> OBInternalAccountIdentification4Code
  OBUltimateDebtor1 --> OBPostalAddress7
  OBWriteDomesticStandingOrder3 --> ActiveOrHistoricCurrencyCode
  OBWriteDomesticStandingOrder3 --> Identification_0
  OBWriteDomesticStandingOrder3 --> NumberOfPayments
  OBWriteDomesticStandingOrder3 --> OBActiveCurrencyAndAmount_SimpleType
  OBWriteDomesticStandingOrder3 --> OBInternalAccountIdentification4Code
  OBWriteDomesticStandingOrder3 --> OBMandateRelatedInformation1
  OBWriteDomesticStandingOrder3 --> OBProxy1
  OBWriteDomesticStandingOrder3 --> OBRegulatoryReporting1
  OBWriteDomesticStandingOrder3 --> OBRemittanceInformation2
  OBWriteDomesticStandingOrder3 --> OBRisk1
  OBWriteDomesticStandingOrder3 --> OBSupplementaryData1
  OBWriteDomesticStandingOrder3 --> OBUltimateCreditor1
  OBWriteDomesticStandingOrder3 --> OBUltimateDebtor1
  OBWriteDomesticStandingOrder3 --> SecondaryIdentification
  OBWriteDomesticStandingOrderConsent5 --> ActiveOrHistoricCurrencyCode
  OBWriteDomesticStandingOrderConsent5 --> Identification_0
  OBWriteDomesticStandingOrderConsent5 --> NumberOfPayments
  OBWriteDomesticStandingOrderConsent5 --> OBActiveCurrencyAndAmount_SimpleType
  OBWriteDomesticStandingOrderConsent5 --> OBInternalAccountIdentification4Code
  OBWriteDomesticStandingOrderConsent5 --> OBMandateRelatedInformation1
  OBWriteDomesticStandingOrderConsent5 --> OBProxy1
  OBWriteDomesticStandingOrderConsent5 --> OBRegulatoryReporting1
  OBWriteDomesticStandingOrderConsent5 --> OBRemittanceInformation2
  OBWriteDomesticStandingOrderConsent5 --> OBRisk1
  OBWriteDomesticStandingOrderConsent5 --> OBSCASupportData1
  OBWriteDomesticStandingOrderConsent5 --> OBSupplementaryData1
  OBWriteDomesticStandingOrderConsent5 --> OBUltimateCreditor1
  OBWriteDomesticStandingOrderConsent5 --> OBUltimateDebtor1
  OBWriteDomesticStandingOrderConsent5 --> SecondaryIdentification
