flowchart TB
  %% Tag overview: International Scheduled Payments
  subgraph International_Scheduled_Payments["International Scheduled Payments"]
    _international_scheduled_payment_consents["/international-scheduled-payment-consents"]
    _international_scheduled_payment_consents_post_CreateInternationalScheduledPaymentConsents["POST\nCreateInternationalScheduledPaymentConsents"]
    _international_scheduled_payment_consents --> _international_scheduled_payment_consents_post_CreateInternationalScheduledPaymentConsents
    _international_scheduled_payment_consents__ConsentId_["/international-scheduled-payment-consents/{ConsentId}"]
    _international_scheduled_payment_consents__ConsentId__get_GetInternationalScheduledPaymentConsentsConsentId["GET\nGetInternationalScheduledPaymentConsentsConsentId"]
    _international_scheduled_payment_consents__ConsentId_ --> _international_scheduled_payment_consents__ConsentId__get_GetInternationalScheduledPaymentConsentsConsentId
    _international_scheduled_payment_consents__ConsentId__funds_confirmation["/international-scheduled-payment-consents/{ConsentId}/funds-confirmation"]
    _international_scheduled_payment_consents__ConsentId__funds_confirmation_get_GetInternationalScheduledPaymentConsentsConsentIdFundsConfirmation["GET\nGetInternationalScheduledPaymentConsentsConsentIdFundsConfirmation"]
    _international_scheduled_payment_consents__ConsentId__funds_confirmation --> _international_scheduled_payment_consents__ConsentId__funds_confirmation_get_GetInternationalScheduledPaymentConsentsConsentIdFundsConfirmation
    _international_scheduled_payments["/international-scheduled-payments"]
    _international_scheduled_payments_post_CreateInternationalScheduledPayments["POST\nCreateInternationalScheduledPayments"]
    _international_scheduled_payments --> _international_scheduled_payments_post_CreateInternationalScheduledPayments
    _international_scheduled_payments__InternationalScheduledPaymentId_["/international-scheduled-payments/{InternationalScheduledPaymentId}"]
    _international_scheduled_payments__InternationalScheduledPaymentId__get_GetInternationalScheduledPaymentsInternationalScheduledPaymentId["GET\nGetInternationalScheduledPaymentsInternationalScheduledPaymentId"]
    _international_scheduled_payments__InternationalScheduledPaymentId_ --> _international_scheduled_payments__InternationalScheduledPaymentId__get_GetInternationalScheduledPaymentsInternationalScheduledPaymentId
  end
