flowchart TB
  %% Tag overview: Payment Details
  subgraph Payment_Details["Payment Details"]
    _domestic_payments__DomesticPaymentId__payment_details["/domestic-payments/{DomesticPaymentId}/payment-details"]
    _domestic_payments__DomesticPaymentId__payment_details_get_GetDomesticPaymentsDomesticPaymentIdPaymentDetails["GET\nGetDomesticPaymentsDomesticPaymentIdPaymentDetails"]
    _domestic_payments__DomesticPaymentId__payment_details --> _domestic_payments__DomesticPaymentId__payment_details_get_GetDomesticPaymentsDomesticPaymentIdPaymentDetails
    _domestic_scheduled_payments__DomesticScheduledPaymentId__payment_details["/domestic-scheduled-payments/{DomesticScheduledPaymentId}/payment-details"]
    _domestic_scheduled_payments__DomesticScheduledPaymentId__payment_details_get_GetDomesticScheduledPaymentsDomesticScheduledPaymentIdPaymentDetails["GET\nGetDomesticScheduledPaymentsDomesticScheduledPaymentIdPaymentDetails"]
    _domestic_scheduled_payments__DomesticScheduledPaymentId__payment_details --> _domestic_scheduled_payments__DomesticScheduledPaymentId__payment_details_get_GetDomesticScheduledPaymentsDomesticScheduledPaymentIdPaymentDetails
    _domestic_standing_orders__DomesticStandingOrderId__payment_details["/domestic-standing-orders/{DomesticStandingOrderId}/payment-details"]
    _domestic_standing_orders__DomesticStandingOrderId__payment_details_get_GetDomesticStandingOrdersDomesticStandingOrderIdPaymentDetails["GET\nGetDomesticStandingOrdersDomesticStandingOrderIdPaymentDetails"]
    _domestic_standing_orders__DomesticStandingOrderId__payment_details --> _domestic_standing_orders__DomesticStandingOrderId__payment_details_get_GetDomesticStandingOrdersDomesticStandingOrderIdPaymentDetails
    _file_payments__FilePaymentId__payment_details["/file-payments/{FilePaymentId}/payment-details"]
    _file_payments__FilePaymentId__payment_details_get_GetFilePaymentsFilePaymentIdPaymentDetails["GET\nGetFilePaymentsFilePaymentIdPaymentDetails"]
    _file_payments__FilePaymentId__payment_details --> _file_payments__FilePaymentId__payment_details_get_GetFilePaymentsFilePaymentIdPaymentDetails
    _international_payments__InternationalPaymentId__payment_details["/international-payments/{InternationalPaymentId}/payment-details"]
    _international_payments__InternationalPaymentId__payment_details_get_GetInternationalPaymentsInternationalPaymentIdPaymentDetails["GET\nGetInternationalPaymentsInternationalPaymentIdPaymentDetails"]
    _international_payments__InternationalPaymentId__payment_details --> _international_payments__InternationalPaymentId__payment_details_get_GetInternationalPaymentsInternationalPaymentIdPaymentDetails
    _international_scheduled_payments__InternationalScheduledPaymentId__payment_details["/international-scheduled-payments/{InternationalScheduledPaymentId}/payment-details"]
    _international_scheduled_payments__InternationalScheduledPaymentId__payment_details_get_GetInternationalScheduledPaymentsInternationalScheduledPaymentIdPaymentDetails["GET\nGetInternationalScheduledPaymentsInternationalScheduledPaymentIdPaymentDetails"]
    _international_scheduled_payments__InternationalScheduledPaymentId__payment_details --> _international_scheduled_payments__InternationalScheduledPaymentId__payment_details_get_GetInternationalScheduledPaymentsInternationalScheduledPaymentIdPaymentDetails
    _international_standing_orders__InternationalStandingOrderPaymentId__payment_details["/international-standing-orders/{InternationalStandingOrderPaymentId}/payment-details"]
    _international_standing_orders__InternationalStandingOrderPaymentId__payment_details_get_GetInternationalStandingOrdersInternationalStandingOrderPaymentIdPaymentDetails["GET\nGetInternationalStandingOrdersInternationalStandingOrderPaymentIdPaymentDetails"]
    _international_standing_orders__InternationalStandingOrderPaymentId__payment_details --> _international_standing_orders__InternationalStandingOrderPaymentId__payment_details_get_GetInternationalStandingOrdersInternationalStandingOrderPaymentIdPaymentDetails
  end
