classDiagram
  %% Schemas related to tag: Funds Confirmations
  class ExternalProxyAccountType1Code
  class OBFundsConfirmation1
  class OBFundsConfirmationConsent1
  class OBProxy1
  OBFundsConfirmationConsent1 --> OBProxy1
  OBProxy1 --> ExternalProxyAccountType1Code
